name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      PATH: ${{ github.workspace }}/android-sdk/cmdline-tools/latest/bin:${{ github.workspace }}/android-sdk/platform-tools:${{ github.workspace }}/android-sdk/emulator:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-dev \
            git zip unzip openjdk-17-jdk tar
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv
          pip install buildozer

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip -d android-sdk
          mkdir -p android-sdk/cmdline-tools/latest
          if [ -d "android-sdk/cmdline-tools/cmdline-tools" ]; then
            mv android-sdk/cmdline-tools/cmdline-tools/* android-sdk/cmdline-tools/latest/
          else
            mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest/
          fi
          yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses

      - name: Build APK with Buildozer
        run: buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: OnlineChat-APK
          path: bin/*.apk
