name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-dev \
            git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install cython==0.29.36 virtualenv
          pip install buildozer

      - name: Install Android SDK
        run: |
          # Android SDK command-line tools-ni yuklab olish
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip -d android-sdk
          # Papka strukturasi yaratish va fayllarni joylashtirish
          mkdir -p android-sdk/cmdline-tools
          mv android-sdk/cmdline-tools/*/* android-sdk/cmdline-tools/latest 2>/dev/null || mv android-sdk/cmdline-tools/* android-sdk/cmdline-tools/latest
          # Environment o'zgaruvchilarini sozlash
          export ANDROID_HOME=$PWD/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          # SDK komponentlarini o'rnatish
          yes | sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"
          # Litsenziyalarni qabul qilish
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OnlineChat-APK
          path: bin/*.apk
