name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk \
            unzip \
            zlib1g-dev \
            libncurses5 \
            libffi-dev \
            libssl-dev \
            git \
            build-essential

          pip install --upgrade pip
          pip install Cython==0.29.36 buildozer

      - name: Install Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          unzip -q sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export ANDROIDNDK=$ANDROIDSDK/ndk-bundle
          export PATH=$ANDROIDSDK/platform-tools:$PATH

          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: bin/*.apk
